# Generated by Django 3.2.9 on 2021-12-04 06:25

from django.db import migrations, models
import siteFinal.models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('fazer', models.CharField(max_length=5000, verbose_name='Fazer')),
                ('fazendo', models.CharField(max_length=5000, verbose_name='Fazendo')),
                ('feito', models.CharField(max_length=5000, verbose_name='Feito')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
            },
        ),
        migrations.CreateModel(
            name='Ternos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('desc', models.TextField(max_length=1000, verbose_name='Desc')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço')),
                ('imagem', stdimage.models.StdImageField(upload_to=siteFinal.models.get_file_path, verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Terno',
                'verbose_name_plural': 'Ternos',
            },
        ),
    ]
